replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/buoyant-site-480804-k1/helm-repo/python-app
  tag: "latest"
  pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
